name: CI

on:
  push:
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies with vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git vcpkg
          ./vcpkg/bootstrap-vcpkg.bat
          ./vcpkg/vcpkg install
          set VCPKG_ROOT=%CD%\vcpkg

      - name: Configure with CMake
        run: |
          cmake -S . -B build ^
            -DCMAKE_TOOLCHAIN_FILE=%CD%\vcpkg\scripts\buildsystems\vcpkg.cmake ^
            -DVCPKG_TARGET_TRIPLET=x64-windows

      - name: Build
        run: cmake --build build --config Release
